---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spree
  labels:
    app: spree
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spree
  template:
    metadata:
      labels:
        app: spree
    spec:
      containers:
      - name: spree
        image: node2:5000/spree
        ports:
        - containerPort: 3000
